export const AUTH_KEY = 'asc_auth_key';
export const LANGUAGE = 'language';
export const ARTICLE_PINNED_KEY = 'asc_article_pinned_key';

/**
 * Enum for employee activation status.
 * @readonly
 */
export const EmployeeActivationStatus = Object.freeze({
  NotActivated: 0,
  Activated: 1,
  Pending: 2,
  AutoGenerated: 4
});

/**
 * Enum for employee status.
 * @readonly
 */
export const EmployeeStatus = Object.freeze({
  Active: 1,
  Disabled: 2
});

/**
 * Enum for employee type.
 * @readonly
 */
export const EmployeeType = Object.freeze({
  User: 1,
  Guest: 2
});

/**
 * Enum for type of email value errors.
 * @readonly
 */
export const parseErrorTypes = Object.freeze({
  None: 0,
  EmptyRecipients: 1,
  IncorrectEmail: 2
});

export const errorKeys = Object.freeze({
  LocalDomain: "LocalDomain",
  IncorrectDomain: "IncorrectDomain",
  DomainIpAddress: "DomainIpAddress",
  PunycodeDomain: "PunycodeDomain",
  PunycodeLocalPart: "PunycodeLocalPart",
  IncorrectLocalPart: "IncorrectLocalPart",
  SpacesInLocalPart: "SpacesInLocalPart",
  MaxLengthExceeded: "MaxLengthExceeded",
  IncorrectEmail: "IncorrectEmail",
  ManyEmails: "ManyEmails",
  EmptyEmail: "EmptyEmail"
});
